# Generated by Django 3.1.4 on 2021-03-02 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professional_Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=10)),
                ('LastName', models.CharField(max_length=10)),
                ('ContactNo', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Professional_mst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=10, unique=True)),
                ('Password', models.CharField(max_length=15)),
                ('FirstName', models.CharField(max_length=10)),
                ('LastName', models.CharField(max_length=10)),
                ('Gender', models.CharField(max_length=1)),
                ('Email', models.CharField(max_length=30, unique=True)),
                ('ContactNo', models.CharField(max_length=10, unique=True)),
                ('Qualification', models.CharField(max_length=50)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('Postcode', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
