# Generated by Django 3.1.4 on 2021-02-25 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof_base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional_mst',
            name='Postcode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='professional_mst',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
