# Generated by Django 3.1.4 on 2021-03-04 07:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usr_base', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking_slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, default=None, max_length=100, null=True, unique=True)),
                ('ServiceName', models.CharField(blank=True, max_length=255, null=True)),
                ('slot', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.CharField(blank=True, max_length=60, null=True)),
                ('datetime_of_payment', models.DateTimeField(default=django.utils.timezone.now)),
                ('professional', models.CharField(blank=True, max_length=60, null=True)),
                ('razorpay_orderId', models.CharField(blank=True, max_length=255, null=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=155, null=True)),
                ('address', models.CharField(blank=True, max_length=600, null=True)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(1, 'PENDING'), (2, 'ACCEPTED'), (3, 'DECLINED'), (4, 'COMPLETE')], default=1)),
                ('payment_status', models.IntegerField(choices=[(1, 'SUCCESS'), (2, 'FAILURE'), (3, 'PENDING')], default=3)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usr_base.user_mst')),
            ],
        ),
        migrations.CreateModel(
            name='Category_mst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryName', models.CharField(db_index=True, max_length=25)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Professional_mst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=10, unique=True)),
                ('Password', models.CharField(max_length=15)),
                ('FirstName', models.CharField(max_length=10)),
                ('LastName', models.CharField(max_length=10)),
                ('Gender', models.CharField(max_length=1)),
                ('Email', models.CharField(max_length=30, unique=True)),
                ('ContactNo', models.CharField(max_length=10, unique=True)),
                ('Qualification', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Service_mst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ServiceName', models.CharField(db_index=True, max_length=355)),
                ('slug', models.SlugField(max_length=455, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='services/%Y/%m/%d')),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('rate', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=5)),
                ('Categoryid', models.ForeignKey(max_length=7, on_delete=django.db.models.deletion.CASCADE, to='admin_base.category_mst')),
                ('Professionalid', models.ForeignKey(max_length=5, on_delete=django.db.models.deletion.CASCADE, to='admin_base.professional_mst')),
            ],
        ),
        migrations.CreateModel(
            name='payment_mst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(blank=True, max_length=155, null=True)),
                ('serviceName', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_id', models.CharField(blank=True, max_length=155, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_base.booking_slot')),
            ],
        ),
    ]
