# Generated by Django 3.1.4 on 2021-01-10 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category_mst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryName', models.CharField(db_index=True, max_length=25)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Professional_mst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=10, unique=True)),
                ('Password', models.CharField(max_length=15)),
                ('FirstName', models.CharField(max_length=10)),
                ('LastName', models.CharField(max_length=10)),
                ('Gender', models.CharField(max_length=1)),
                ('Email', models.CharField(max_length=30, unique=True)),
                ('ContactNo', models.CharField(max_length=10, unique=True)),
                ('Qualification', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Service_mst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ServiceName', models.CharField(db_index=True, max_length=20)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='services/%Y/%m/%d')),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('Categoryid', models.ForeignKey(max_length=7, on_delete=django.db.models.deletion.CASCADE, to='admin_base.category_mst')),
                ('Professionalid', models.ForeignKey(max_length=5, on_delete=django.db.models.deletion.CASCADE, to='admin_base.professional_mst')),
            ],
        ),
    ]
