# Generated by Django 3.1.4 on 2021-03-02 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_slot',
            name='order_id',
            field=models.CharField(default='005D6', editable=False, max_length=50, primary_key=True, serialize=False),
        ),
    ]
