# Generated by Django 3.1.4 on 2021-03-04 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking_slot',
            old_name='User',
            new_name='UserName',
        ),
    ]
