# Generated by Django 3.1.4 on 2021-03-04 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_base', '0003_auto_20210304_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional_mst',
            name='Gender',
            field=models.CharField(choices=[('F', 'F'), ('M', 'M')], default=1, max_length=1),
        ),
    ]
