# Generated by Django 3.1.4 on 2021-03-04 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usr_base', '0001_initial'),
        ('admin_base', '0004_auto_20210304_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback_mst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=155, null=True)),
                ('feedback', models.TextField(null=True)),
                ('Professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedprofessional', to='admin_base.professional_mst')),
                ('UserName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeduser', to='usr_base.user_mst')),
            ],
        ),
    ]
