# Generated by Django 3.1.4 on 2021-03-04 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_base', '0005_feedback_mst'),
    ]

    operations = [
        migrations.DeleteModel(
            name='payment_mst',
        ),
    ]
