# Generated by Django 3.1.4 on 2021-03-04 18:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admin_base', '0006_delete_payment_mst'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback_mst',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date'),
            preserve_default=False,
        ),
    ]
