# Generated by Django 3.1.4 on 2021-03-04 18:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_base', '0008_auto_20210305_0022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback_mst',
            name='date',
        ),
        migrations.AddField(
            model_name='feedback_mst',
            name='Date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
