# Generated by Django 3.1.4 on 2021-03-04 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_base', '0010_feedback_mst_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback_mst',
            name='ServiceName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
