# Generated by Django 3.1.4 on 2021-03-05 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_base', '0011_feedback_mst_servicename'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_slot',
            name='Reviews',
            field=models.BooleanField(default=False),
        ),
    ]
