# Generated by Django 3.1.4 on 2021-03-02 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contactus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=50)),
                ('Message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User_mst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=55, unique=True)),
                ('Password', models.CharField(max_length=500)),
                ('FirstName', models.CharField(max_length=25)),
                ('LastName', models.CharField(max_length=25)),
                ('Gender', models.CharField(max_length=1)),
                ('Email', models.CharField(max_length=60, unique=True)),
                ('ContactNo', models.CharField(max_length=10, unique=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('Postcode', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
