# Generated by Django 3.1.4 on 2021-02-04 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usr_base', '0002_auto_20210120_2246'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=25, unique=True)),
                ('email', models.CharField(max_length=50)),
                ('Message', models.CharField(max_length=1000)),
            ],
        ),
    ]
