# Generated by Django 3.1.4 on 2021-02-04 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usr_base', '0003_contactus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='Message',
            field=models.TextField(),
        ),
    ]
