# Generated by Django 3.1.4 on 2021-02-11 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usr_base', '0005_auto_20210205_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_mst',
            name='Email',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='user_mst',
            name='FirstName',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='user_mst',
            name='LastName',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='user_mst',
            name='UserName',
            field=models.CharField(max_length=55, unique=True),
        ),
    ]
