# Generated by Django 3.1.4 on 2021-02-24 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usr_base', '0006_auto_20210211_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_mst',
            name='Postcode',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user_mst',
            name='address',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
