# Generated by Django 3.1.4 on 2021-02-24 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usr_base', '0007_auto_20210224_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_mst',
            name='Postcode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user_mst',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
